spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/messenger
    username: postgres
    password: test

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
##      group-id: test_group
##      auto-offset-reset: earliest
##      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
##      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#
#kafka:
#  testProducer:
#    topic: test_topic

